---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# PCAtest

<!-- badges: start -->
<!-- badges: end -->

The goal of PCAtest is to evaluate the overall significance of a PCA, of each PC axis, and of the contributions of each observed variable to the significant axes based on permutation-based statistical tests.

## Installation

You can install the released and the development versions from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("arleyc/PCAtest")
```
## Example

```{r example1}
library(PCAtest)
# PCA analysis of two uncorrelated variables
v1<-runif(100,0,1)
v2<-runif(100,0,1)
x<-cbind(v1,v2)
result<-PCAtest(x, 100, 100, 0.05, corr=FALSE, plot=TRUE)
```

```{r example2}
#PCA analysis of two fully-correlated variables
v1<-seq(0,1,0.01)
v2<-seq(0,1,0.01)
x<-cbind(v1,v2)
PCAout<-PCAtest(x, 100, 100, 0.05, corr=FALSE, plot=TRUE)
```
